# Generated by Django 3.1.7 on 2021-03-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Janeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(max_length=10)),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
